spring:
  jpa:
    show-sql : true
    properties:
      hibernate:
        format_sql: true
        ddl-auto: create
  datasource:
    url: jdbc:h2:mem:ecomDb;DB_CLOSE_DELAY=-1
    username: sa
    password:
    platform: h2
    driverClassName: org.h2.Driver
  h2:
    console:
      enabled: true

#spring:
#  datasource:
#    driverClassName: com.mysql.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/ecomDb
#    username: root
#    password:
#  jpa:
#    hibernate.ddl-auto: create
#    generate-ddl: true
#    show-sql: true